package XmlFinal;


/**
* XmlFinal/dataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 7 de diciembre de 2017 02:42:20 AM CST
*/

public final class dataHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public dataHolder ()
  {
  }

  public dataHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = XmlFinal.dataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    XmlFinal.dataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return XmlFinal.dataHelper.type ();
  }

}
