package XmlFinal;


/**
* XmlFinal/XMLEstructPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 7 de diciembre de 2017 02:42:20 AM CST
*/

public abstract class XMLEstructPOA extends org.omg.PortableServer.Servant
 implements XmlFinal.XMLEstructOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("upload", new java.lang.Integer (0));
    _methods.put ("getXML", new java.lang.Integer (1));
    _methods.put ("getXMLDetail", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // XmlFinal/XMLEstruct/upload
       {
         String fileName = in.read_string ();
         String fileString = in.read_string ();
         String $result = null;
         $result = this.upload (fileName, fileString);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // XmlFinal/XMLEstruct/getXML
       {
         String $result[] = null;
         $result = this.getXML ();
         out = $rh.createReply();
         XmlFinal.dataHelper.write (out, $result);
         break;
       }

       case 2:  // XmlFinal/XMLEstruct/getXMLDetail
       {
         String name = in.read_string ();
         String $result = null;
         $result = this.getXMLDetail (name);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // XmlFinal/XMLEstruct/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:XmlFinal/XMLEstruct:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public XMLEstruct _this() 
  {
    return XMLEstructHelper.narrow(
    super._this_object());
  }

  public XMLEstruct _this(org.omg.CORBA.ORB orb) 
  {
    return XMLEstructHelper.narrow(
    super._this_object(orb));
  }


} // class XMLEstructPOA
