package XmlFinal;


/**
* XmlFinal/XMLEstructOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 7 de diciembre de 2017 02:42:21 AM CST
*/

public interface XMLEstructOperations 
{
  String upload (String fileName, String fileString);
  String[] getXML ();
  String getXMLDetail (String name);
  void shutdown ();
} // interface XMLEstructOperations
