package XmlFinal;


/**
* XmlFinal/XMLEstructHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 7 de diciembre de 2017 02:42:21 AM CST
*/

abstract public class XMLEstructHelper
{
  private static String  _id = "IDL:XmlFinal/XMLEstruct:1.0";

  public static void insert (org.omg.CORBA.Any a, XmlFinal.XMLEstruct that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static XmlFinal.XMLEstruct extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (XmlFinal.XMLEstructHelper.id (), "XMLEstruct");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static XmlFinal.XMLEstruct read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_XMLEstructStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, XmlFinal.XMLEstruct value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static XmlFinal.XMLEstruct narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof XmlFinal.XMLEstruct)
      return (XmlFinal.XMLEstruct)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      XmlFinal._XMLEstructStub stub = new XmlFinal._XMLEstructStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static XmlFinal.XMLEstruct unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof XmlFinal.XMLEstruct)
      return (XmlFinal.XMLEstruct)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      XmlFinal._XMLEstructStub stub = new XmlFinal._XMLEstructStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
