package XmlFinal;


/**
* XmlFinal/XMLEstruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 7 de diciembre de 2017 02:42:21 AM CST
*/

public interface XMLEstruct extends XMLEstructOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface XMLEstruct
