package XmlFinal;

/**
* XmlFinal/XMLEstructHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* jueves 7 de diciembre de 2017 02:42:21 AM CST
*/

public final class XMLEstructHolder implements org.omg.CORBA.portable.Streamable
{
  public XmlFinal.XMLEstruct value = null;

  public XMLEstructHolder ()
  {
  }

  public XMLEstructHolder (XmlFinal.XMLEstruct initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = XmlFinal.XMLEstructHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    XmlFinal.XMLEstructHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return XmlFinal.XMLEstructHelper.type ();
  }

}
